const mongoose = require("mongoose")

const ProjectSchema = new mongoose.Schema({
  id: { type: String, required: true, unique: true, index: true },
  customer: { type: String, required: true, trim: true },
  name: { type: String, required: true, trim: true },
  plantId: { type: String, required: true, trim: true, index: true },
  plant: { type: String, trim: true, default: "" },
  rfqNo: { type: String, trim: true, default: "" },
  apqpNo: { type: String, trim: true, default: "" },
  vehicleModel: { type: String, trim: true, default: "" },
  partCode: { type: String, required: true, trim: true },
  sopDate: { type: String, required: true, trim: true },
  sopVolume: { type: String, trim: true, default: "" },
  startDate: { type: String, trim: true, default: "" },
  endDate: { type: String, trim: true, default: "" },
  projectLeadId: { type: String, trim: true, default: "" },
  projectLead: { type: String, required: true, trim: true },
  departmentId: { type: String, trim: true, default: "" },
  cftMemberIds: { type: [String], default: [] },
  cftMembers: { type: [String], default: [] },
  status: { type: String, trim: true, default: "Active" },
  description: { type: String, default: "" },
  selectedTasks: { type: [String], default: [] },
  drs: { type: [mongoose.Schema.Types.Mixed], default: [] },
  workflowTasks: { type: [mongoose.Schema.Types.Mixed], default: [] },
  projectFiles: { type: [mongoose.Schema.Types.Mixed], default: [] },
  notifiedUserIds: { type: [String], default: [] },
  notificationChannels: { type: [String], default: [] },
  phase: { type: String, trim: true, default: "" },
  progress: { type: Number, default: 0 },
  createdById: { type: String, trim: true, default: "" },
  createdByName: { type: String, trim: true, default: "" },
  pendingApprovalRequest: { type: mongoose.Schema.Types.Mixed, default: null },
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
})

module.exports = mongoose.model("Project", ProjectSchema)
